=== MEB-AH-Hackathon/hackathon/KEY_INFO/pdf_vaccine_names_only_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "PDF Vaccine Names Only Schema",
  "description": "Mapping between PDF filenames and vaccine names",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "filename": {"type": "string", "description": "PDF filename"},
      "vax_type": {"type": "string", "description": "CDC vaccine type abbreviation"},
      "vax_name": {"type": "string", "description": "Full vaccine name in VAERS format"},
      "vax_manu": {"type": "string", "description": "Manufacturer name"}
    },
    "required": ["filename", "vax_type", "vax_name", "vax_manu"]
  }
}

=== MEB-AH-Hackathon/hackathon/json_data/pdf_vaccine_names_only.json
[
  {
    "filename": "BCG.pdf",
    "vax_type": "BCG",
    "vax_name": "BCG LIVE (TICE\u00ae BCG)",
    "vax_manu": "ORGANON TEKNIKA CORPORATION LLC"
  },
  {
    "filename": "Package Insert - Adenovirus Type 4 and Type 7 Vaccine, Live, Oral_0.pdf",
    "vax_type": "UNKNOWN",
    "vax_name": "ADENOVIRUS TYPE 4 AND TYPE 7 VACCINE, LIVE, ORAL",
    "vax_manu": "TEVA PHARMACEUTICALS USA, INC."
  },
  {
    "filename": "Package Insert - SPIKEVAX_0.pdf",
    "vax_type": "COVID19",
    "vax_name": "COVID19 (SPIKEVAX)",
    "vax_manu": "MODERNA US, INC."
  },
  {
    "filename": "Package Insert - TICOVACpdf.pdf",
    "vax_type": "TBE",
    "vax_name": "TICOVAC (TICK-BORNE ENCEPHALITIS VACCINE)",
    "vax_manu": "PFIZER IRELAND PHARMACEUTICALS"
  },
  {
    "filename": "Package-Insert---BCG-Vaccine.pdf",
    "vax_type": "BCG",
    "vax_name": "BCG VACCINE (TICE\u00ae STRAIN)",
    "vax_manu": "ORGANON TEKNIKA CORPORATION LLC"
  },
  {
    "filename": "Package-Insert-Adacel.pdf",
    "vax_type": "TDAP",
    "vax_name": "TETANUS TOXOID, REDUCED DIPHTHERIA TOXOID AND ACELLULAR PERTUSSIS VACCINE ADSORBED (ADACEL)",
    "vax_manu": "SANOFI PASTEUR INC."
  },
  {
    "filename": "Package-Insert-CYFENDUS.pdf",
    "vax_type": "COVID19",
    "vax_name": "ANTHRAX VACCINE ADSORBED, ADJUVANTED (CYFENDUS)",
    "vax_manu": "EMERGENT BIODEFENSE OPERATIONS LANSING LLC"
  },
  {
    "filename": "Package-Insert-DAPTACEL.pdf",
    "vax_type": "DTAP",
    "vax_name": "DIPHTHERIA AND TETANUS TOXOIDS AND ACELLULAR PERTUSSIS VACCINE ADSORBED (DAPTACEL)",
    "vax_manu": "SANOFI PASTEUR INC."
  },
  {
    "filename": "Package-Insert-DENGVAXIA.pdf",
    "vax_type": "DENGUE",
    "vax_name": "DENGUE (DENGVAXIA)",
    "vax_manu": "SANOFI PASTEUR INC."
  },
  {
    "filename": "Package-Insert-HAVRIX.pdf",
    "vax_type": "HEPA",
    "vax_name": "HEPATITIS A (HAVRIX)",
    "vax_manu": "GLAXOSMITHKLINE BIOLOGICALS"
  },
  {
    "filename": "Package-Insert-INFANRIX_4.pdf",
    "vax_type": "DTAP",
    "vax_name": "DIPHTHERIA AND TETANUS TOXOIDS AND ACELLULAR PERTUSSIS (INFANRIX)",
    "vax_manu": "GLAXOSMITHKLINE BIOLOGICALS"
  },
  {
    "filename": "Package-Insert-KINRIX_1.pdf",
    "vax_type": "DTaP-IPV",
    "vax_name": "DIPHTHERIA AND TETANUS TOXOIDS AND ACELLULAR PERTUSSIS ADSORBED AND INACTIVATED POLIOVIRUS VACCINE (KINRIX)",
    "vax_manu": "GLAXOSMITHKLINE BIOLOGICALS"
  },
  {
    "filename": "Package-Insert-PEDIARIX_1.pdf",
    "vax_type": "DTP-HEPB-IPV",
    "vax_name": "DIPHTHERIA AND TETANUS TOXOIDS AND ACELLULAR PERTUSSIS ADSORBED, HEPATITIS B (RECOMBINANT) AND INACTIVATED POLIOVIRUS VACCINE (PEDIARIX)",
    "vax_manu": "GLAXOSMITHKLINE BIOLOGICALS"
  },
  {
    "filename": "Package-Insert-Pentacel-(inactivated-poliovirus-component-grown-in-MRC-5-cells).pdf",
    "vax_type": "DTAP-IPV-HIB",
    "vax_name": "PENTACEL (DIPHTHERIA AND TETANUS TOXOIDS AND ACELLULAR PERTUSSIS ADSORBED, INACTIVATED POLIOVIRUS AND HAEMOPHILUS B CONJUGATE (TETANUS TOXOID CONJUGATE) VACCINE)",
    "vax_manu": "SANOFI PASTEUR"
  },
  {
    "filename": "Package-Insert-Pentacel-(inactivated-poliovirus-component-grown-in-Vero-cells.pdf",
    "vax_type": "DTAP-IPV-HIB",
    "vax_name": "DIPHTHERIA AND TETANUS TOXOIDS AND ACELLULAR PERTUSSIS ADSORBED, INACTIVATED POLIOVIRUS AND HAEMOPHILUS B CONJUGATE (TETANUS TOXOID CONJUGATE) VACCINE (PENTACEL)",
    "vax_manu": "SANOFI PASTEUR"
  },
  {
    "filename": "Package-Insert-Quadracel-(inactivated-poliovirus-component-grown-in-MRC-5-cells).pdf",
    "vax_type": "DTAP-IPV",
    "vax_name": "DIPHTHERIA AND TETANUS TOXOIDS AND ACELLULAR PERTUSSIS ADSORBED AND INACTIVATED POLIOVIRUS VACCINE (QUADRACEL)",
    "vax_manu": "SANOFI PASTEUR"
  },
  {
    "filename": "Package-Insert-Quadracel-(inactivated-poliovirus-component-grown-in-Vero-cells)_0.pdf",
    "vax_type": "DTaP-IPV",
    "vax_name": "DIPHTHERIA AND TETANUS TOXOIDS AND ACELLULAR PERTUSSIS ADSORBED AND INACTIVATED POLIOVIRUS VACCINE (QUADRACEL)",
    "vax_manu": "SANOFI PASTEUR"
  },
  {
    "filename": "Package-Insert-SHINGRIX (1).pdf",
    "vax_type": "ZOSTER",
    "vax_name": "SHINGRIX (ZOSTER VACCINE RECOMBINANT, ADJUVANTED)",
    "vax_manu": "GLAXOSMITHKLINE BIOLOGICALS"
  },
  {
    "filename": "Package-Insert-SHINGRIX.pdf",
    "vax_type": "ZOSTER",
    "vax_name": "SHINGRIX (ZOSTER VACCINE RECOMBINANT, ADJUVANTED)",
    "vax_manu": "GLAXOSMITHKLINE BIOLOGICALS"
  },
  {
    "filename": "Package-Insert-Typhim-Vi.pdf",
    "vax_type": "TYPHOID",
    "vax_name": "TYPHOID VI POLYSACCHARIDE VACCINE (TYPHIM VI)",
    "vax_manu": "SANOFI PASTEUR SA"
  },
  {
    "filename": "Package-Insert-VAXELIS_1.pdf",
    "vax_type": "DTAPHEPBHIB",
    "vax_name": "VAXELIS (DIPHTHERIA AND TETANUS TOXOIDS AND ACELLULAR PERTUSSIS, INACTIVATED POLIOVIRUS, HAEMOPHILUS B CONJUGATE AND HEPATITIS B VACCINE)",
    "vax_manu": "SANOFI PASTEUR LIMITED"
  },
  {
    "filename": "Package-Insert-YF-Vax_0.pdf",
    "vax_type": "YF",
    "vax_name": "YELLOW FEVER (YF-VAX)",
    "vax_manu": "SANOFI PASTEUR INC."
  },
  {
    "filename": "Package-Insert-and-Information-for-Patients---Biothrax.pdf",
    "vax_type": "UNKNOWN",
    "vax_name": "ANTHRAX VACCINE ADSORBED (BIOTHRAX)",
    "vax_manu": "EMERGENT BIOSOLUTIONS"
  },
  {
    "filename": "Package-Insert-and-Patient-Information-(Squeezable-Tube-Presentation)-ROTARIX.pdf",
    "vax_type": "ROTARIX",
    "vax_name": "ROTARIX (ROTAVIRUS VACCINE, LIVE, ORAL)",
    "vax_manu": "GLAXOSMITHKLINE BIOLOGICALS"
  },
  {
    "filename": "Package-Insert-and-Patient-Information-(Vial-with-Oral Dosing-Applicator-Presentation-and-Oral-Dosing-Applicator-Only-Presentation)-ROTARIX.pdf",
    "vax_type": "RV",
    "vax_name": "ROTARIX (ROTAVIRUS VACCINE, LIVE, ORAL)",
    "vax_manu": "GLAXOSMITHKLINE BIOLOGICALS"
  },
  {
    "filename": "Package-Insert-and-Patient-Information-IXIARO_0.pdf",
    "vax_type": "JEV",
    "vax_name": "JAPANESE ENCEPHALITIS VACCINE, INACTIVATED, ADSORBED (IXIARO)",
    "vax_manu": "VALNEVA AUSTRIA GMBH"
  },
  {
    "filename": "Td Package Insert -010301 April 2009.pdf",
    "vax_type": "TD",
    "vax_name": "TETANUS AND DIPHTHERIA TOXOIDS ADSORBED (TDVAX)",
    "vax_manu": "MASSBIOLOGICS"
  },
  {
    "filename": "ZOSTAVAX (Zoster Vaccine Live) Frozen Package Insert.pdf",
    "vax_type": "ZOSTER",
    "vax_name": "ZOSTER VACCINE LIVE (ZOSTAVAX)",
    "vax_manu": "MERCK & CO. INC."
  },
  {
    "filename": "ZOSTAVAX (Zoster vaccine Live) Refrigerated Package Insert.pdf",
    "vax_type": "ZOSTER",
    "vax_name": "ZOSTER VACCINE LIVE (ZOSTAVAX)",
    "vax_manu": "MERCK & CO. INC."
  },
  {
    "filename": "package-insert-gardasil (1).pdf",
    "vax_type": "HPV4",
    "vax_name": "HUMAN PAPILLOMAVIRUS QUADRIVALENT (TYPES 6, 11, 16, AND 18) VACCINE, RECOMBINANT (GARDASIL)",
    "vax_manu": "MERCK & CO. INC."
  },
  {
    "filename": "package-insert-gardasil.pdf",
    "vax_type": "HPV4",
    "vax_name": "HUMAN PAPILLOMAVIRUS QUADRIVALENT (TYPES 6, 11, 16, AND 18) VACCINE, RECOMBINANT (GARDASIL)",
    "vax_manu": "MERCK & CO. INC."
  },
  {
    "filename": "package-insert-mnexspike_0.pdf",
    "vax_type": "COVID19",
    "vax_name": "COVID19 (COVID19 (MNEXSPIKE))",
    "vax_manu": "MODERNA US, INC."
  },
  {
    "filename": "package-insert-vaxchora.pdf",
    "vax_type": "COVID19",
    "vax_name": "CHOLERA VACCINE, LIVE, ORAL (VAXCHORA)",
    "vax_manu": "EMERGENT TRAVEL HEALTH INC."
  },
  {
    "filename": "package-insert-vimkunya.pdf",
    "vax_type": "COVID19",
    "vax_name": "VIMKUNYA (CHIKUNGUNYA VACCINE, RECOMBINANT)",
    "vax_manu": "BAVARIAN NORDIC A/S"
  }
]
